replicaCount: 1

image:
  repository: louislam/uptime-kuma
  pullPolicy: IfNotPresent
  tag: "latest"
  containerPort: 3001

service:
  type: ClusterIP
  port: 3001
  
persistence:
  enabled: true
  storageClassName: "longhorn"
  accessMode: ReadWriteMany
  size: 2Gi

ingress:
  enabled: true
  ingressClass: nginx
  annotations: 
    kubernetes.io/ingress.class: nginx
  paths:
    - /
  hosts:
    - name: uptime.internal.oceanai.io
  tls:
    - hosts:
        - uptime.internal.oceanai.io

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
